apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: aob-payment-service
        image: 13.127.243.52:5000/aob-payments-service:VERSION
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 3025
        env:
        - name: LOG_FILE_SETTING_PATH
          valueFrom:
            configMapKeyRef:
              name: environment-configmap
              key: PAYMENT_LOG_FILE_SETTING_PATH
        - name: GLOBAL_APP_SETTING_PATH
          valueFrom:
            configMapKeyRef:
              name: environment-configmap
              key: GLOBAL_APP_SETTING_PATH
        - name: SERVICE_APP_SETTING_PATH
          valueFrom:
            configMapKeyRef:
              name: environment-configmap
              key: PAYMENT_SERVICE_APP_SETTING_PATH
        volumeMounts:
        - mountPath: /etc/properties/app
          name: application-properties
        - mountPath: /etc/properties/service
          name: service-properties
        - mountPath: /var/log/applogs/
          name: log-path
      volumes:
      - name: application-properties
        configMap:
          name:  application-configmap
      - name: service-properties
        configMap:
          name:  payment-configmap
      - name: log-path
        hostPath:
          path: /var/logs/application/payment-service

---

kind: Service
apiVersion: v1
metadata:
  name: payment-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3025
    nodePort: 31181
  selector:
     app: payment-service